server:
  port: 8080
  servlet:
    context-path: /web
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/web"
    username: root
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
